### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrZanerson** [byt3bl33d3r/SILENTTRINITY#75] opened 2019-08-20 11:59 UTC
Thanks for the awesome work! 

I tried to setup/install ST on Kali linux arm and amd64bit followed your step by step instructions however the dependecies fails to install.

OS 
Linux nix 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

errors:

An error occurred while installing aiofiles==0.4.0  
An error occurred while installing cryptography==2.7
An error occurred while installing hypercorn==0.6.0
An error occurred while installing hyperframe==5.2.0 
An error occurred while installing multidict==4.5.2
An error occurred while installing pycparser==2.19 

As per your instructions  -  python3.7 installed, i also tried pipenv throws similar issues. 
git clone https://github.com/byt3bl33d3r/SILENTTRINITY
pip3 install pipenv && pipenv install && pipenv shell

Any suggestions ideas? Thanks

**Comment by byt3bl33d3r** [comment] 2019-08-20 21:36
@MrZanerson If you try to install only one of the dependencies with pip3 does it give you any errors in the output?
This is definitely not a bug within ST itself and rather a problem with your system so I'm going to close this. Feel free to comment below and I'll help if i can

**Closed by byt3bl33d3r** 2019-08-20 21:36 UTC
