### ISSUE TITLE
Error when running ipy/powershell module

### ISSUE THREAD

**Issue by hausec** [byt3bl33d3r/SILENTTRINITY#38] opened 2019-02-08 20:59 UTC
# Issue Template

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version: 0.1.0
* Operating System: Kali 2018.4 & Also tried on Ubuntu 16.04
* Python Version: 3.7 

## Expected Behavior
Run a powershell command. 

## Current Behavior

Throws an error:
Exception when executing command run_ipy_script: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.

### Steps to Reproduce

Used msbuild to create agent. I cannot run any command, whether it's just 'dir' or 'ping', I get the same error.

### Failure Logs

ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:44,850] 192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 748 19450                 
INFO:quart.serving:192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 748 19450
                               [2019-02-08 15:58:44,925] DEBUG in http: Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 (192.168.1.167) checked in
DEBUG:quart.app:Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 (192.168.1.167) checked in                                                                   
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:44,933] 192.168.1.167:50998 GET /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs 1.1 200 1456 7964             
INFO:quart.serving:192.168.1.167:50998 GET /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs 1.1 200 1456 7964
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:45,315] 192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 747 26288                 
INFO:quart.serving:192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 747 26288
                               [2019-02-08 15:58:45,389] DEBUG in http: Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 posted results of job odTHLXlJ
DEBUG:quart.app:Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 posted results of job odTHLXlJ                                                               
[+] aa219fb6-8e99-4e23-a7e4-1142a83a5590 returned job result (id: odTHLXlJ)
Exception when executing command run_ipy_script: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:45,399] 192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs/odTHLXlJ 1.1 200 0 17911     
INFO:quart.serving:192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs/odTHLXlJ 1.1 200 0 17911

**Comment by davidtavarez** [comment] 2019-02-08 21:02
```
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:44,850] 192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 748 19450
INFO:quart.serving:192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 748 19450
[2019-02-08 15:58:44,925] DEBUG in http: Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 (192.168.1.167) checked in
DEBUG:quart.app:Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 (192.168.1.167) checked in
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:44,933] 192.168.1.167:50998 GET /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs 1.1 200 1456 7964
INFO:quart.serving:192.168.1.167:50998 GET /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs 1.1 200 1456 7964
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:45,315] 192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 747 26288
INFO:quart.serving:192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590 1.1 200 747 26288
[2019-02-08 15:58:45,389] DEBUG in http: Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 posted results of job odTHLXlJ
DEBUG:quart.app:Session aa219fb6-8e99-4e23-a7e4-1142a83a5590 posted results of job odTHLXlJ
[+] aa219fb6-8e99-4e23-a7e4-1142a83a5590 returned job result (id: odTHLXlJ)
Exception when executing command run_ipy_script: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
ST (modules)(ipy/powershell) ≫ [2019-02-08 15:58:45,399] 192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs/odTHLXlJ 1.1 200 0 17911
INFO:quart.serving:192.168.1.167:50998 POST /aa219fb6-8e99-4e23-a7e4-1142a83a5590/jobs/odTHLXlJ 1.1 200 0 17911
```

**Comment by daddycocoaman** [comment] 2019-02-08 21:38
Can you provide info about the target environment? OS, Powershell Version, .NET Version, etc. This error suggests the Powershell.Create() throws an error when trying to create the PowerShell instance. 

Do you get the same error when you try to run a powershell command through `ipy/shell`?

**Comment by hausec** [comment] 2019-02-09 02:17
> Can you provide info about the target environment? OS, Powershell Version, .NET Version, etc. This error suggests the Powershell.Create() throws an error when trying to create the PowerShell instance.
> 
> Do you get the same error when you try to run a powershell command through `ipy/shell`?

Target is Windows 10, PS version 5.1, .NET 4.0

Running ipy/shell works.

**Comment by byt3bl33d3r** [comment] 2019-02-09 17:46
@hausec I've already ran into this when building the new winrm module, i'm not entirely sure what the cause is since if you just run the code through an installed ipy interpreter it works so I'm assuming it's just a bug that affects the embedded engine. I do have a couple of ideas on potential fixes which i'll try out today.

**Comment by byt3bl33d3r** [comment] 2019-02-12 00:08
Ok so i figured out the cause of this, it's an error in the assembly resolving logic the C# stager uses. I need to refactor the entire thing anyway in order to support spinning up IPY engines in different AppDomains so i'll address it then. 

Also just FYI for anyone who comes across this issue, all the PowerShell stuff in ST is there just for convenience, by using it you are defeating the purpose of using this tool in the first place :)

**Comment by byt3bl33d3r** [comment] 2019-08-07 19:28
Fixed.
Cheers

**Closed by byt3bl33d3r** 2019-08-07 19:28 UTC
Labels: bug
