### ISSUE TITLE
SSLError when new session is connected (ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify)

### ISSUE THREAD

**Issue by eksperience** [byt3bl33d3r/SILENTTRINITY#41] opened 2019-02-10 17:57 UTC
* SILENTTRINITY Version: 0.1.0dev (c2_crypt)
* Operating System: Latest Kali Linux
* Python Version: 3.7.2
* Listener: HTTPS
* Stager: msbuild
* Victim OS: Windows 10 Pro (10.0.17763.0)

When a new session is connected, SSLErrors start spamming out.
However, the session remains alive and can run modules without problems.

![error](https://user-images.githubusercontent.com/44943222/52537316-ffee4000-2d6d-11e9-93a8-281f1bfcea90.png)

**Comment by byt3bl33d3r** [comment] 2019-02-11 17:44
I'm having a hard time reproducing these SSL issues, can you send me a PCAP ?

**Comment by eksperience** [comment] 2019-02-11 23:14
Of course!
Tried to debug this myself without any luck.
[sslerrors.zip](https://github.com/byt3bl33d3r/SILENTTRINITY/files/2853412/sslerrors.zip)

**Comment by adar0n** [comment] 2019-02-15 13:27
Hello Marcello, 
I am having the same issue, kali fresh installed, git clone this morning, while using https listener, imediately after stager connecting back, it throws these errors. Still the modules still run, if I ignore the errors. ipy/systeminfo returns data corectly, even errors appear; 

ERROR:asyncio:SSL error in data received                                             
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f86e450ba90>                                   
transport: <_SelectorSocketTransport fd=14 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

**Comment by CyberTheReape** [comment] 2019-02-28 15:12
same problem ... did you handle this problem ?

**Comment by byt3bl33d3r** [comment] 2019-03-22 20:14
So I was able to reproduce this, after doing some digging this error seems to be related to https://github.com/aio-libs/aiohttp/issues/3535, its a bug that seems to only affect aiohttp/asyncio in python 3.7. It doesn't seem like theres a fix currently or a way to at least make the error message go away. Hopefully this will be fixed in the underlying libraries soon.

**Comment by byt3bl33d3r** [comment] 2019-03-22 20:46
Also this error seems to only happen on Kali, I could not reproduce this on Mac or Debian

**Comment by cpython-rocks** [comment] 2019-04-16 01:08
I can reproduce this issue on Mac/

Python 3.7.1 and aiohttp 3.5.4

**Comment by brookxs** [comment] 2019-07-18 08:02
I  have the same issue on Mac
Python 3.7.4 and aiohttp 3.5.4
and  I can't catch the exception when I used the except Exception.

**Comment by pielgrzym** [comment] 2019-10-04 05:41
Same issue on debian 10.1 - using silent trinity from commit cf13b108a16bcf8d0b33bf7401b15cc8403e31bc. For me the issue arises after ~12-20 hours of work. It apparently causes all the implants to die, since they do not reconnect back. Also I can't connect to the server with my username - I have to switch one (but this might be an unrelated issue).

**Comment by pielgrzym** [comment] 2019-10-04 05:51
Apparently running python 3.7.4 [fixes the issue](https://github.com/aio-libs/aiohttp/issues/3535#issuecomment-497469002). I'll let you know if it worked.

**Comment by pielgrzym** [comment] 2019-10-07 09:40
This (above) definitely fixes the issue - server hasn't died on me for 3 days, all stagers working flawlessly.

**Comment by byt3bl33d3r** [comment] 2019-10-15 20:12
Yeah I haven't seen this error either in a long time. Closing.

**Closed by byt3bl33d3r** 2019-10-15 20:12 UTC
Labels: bug, third-party
